FROM node:14

# Atualizar e instalar bash se necessário
RUN apt-get update && apt-get install -y bash

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar os arquivos do projeto
COPY . .

# Instalar as dependências
RUN npm install

# Garantir que o react-scripts e outros binários no node_modules tenham permissões de execução
RUN chmod -R 755 ./node_modules/.bin

# Construir a aplicação
RUN npm run build

# Expor a porta
EXPOSE 3000

# Iniciar o aplicativo
CMD ["npm", "start"]
