# Usar uma imagem base do Node.js
FROM node:14

# Definir o diretório de trabalho no contêiner
WORKDIR /app

# Copiar apenas os arquivos de configuração para o cache de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante dos arquivos do backend para o contêiner
COPY . .

# Expor a porta onde o backend será executado
EXPOSE 5000

# Comando para iniciar o servidor backend
CMD ["npm", "start"]
