name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Test Frontend
        working-directory: ./frontend
        run: |
          docker build -t myrepo/frontend .
          # Adicionar testes se houver

      - name: Build and Test Backend
        working-directory: ./backend
        run: |
          docker build -t myrepo/backend .
          # Adicionar testes se houver

      - name: Build Database Image
        run: docker pull postgres:13
