name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image for frontend
        run: |
          docker build -t myrepo/frontend:latest ./frontend
          docker run --rm myrepo/frontend:latest npm test

  build_and_test_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image for backend
        run: |
          docker build -t myrepo/backend:latest ./backend
          docker run --rm myrepo/backend:latest npm test

  build_and_test_postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test PostgreSQL connection
        run: |
          docker run --rm postgres:13 psql -U admin -c "SELECT 1;"
