name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Frontend Image
        working-directory: ./frontend
        run: |
          docker build -t myrepo/frontend .
          docker push myrepo/frontend

      - name: Push Backend Image
        working-directory: ./backend
        run: |
          docker build -t myrepo/backend .
          docker push myrepo/backend

      - name: Deploy Simulation
        run: echo "Deploying to simulated production environment"
